#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import pandas as pd 
import numpy as np



#The objective of this code is to expand the conversion done by converter.m

#This directory must point to the csvs generated by converter1.m
directory = "Datasets/simtbTemp.csv"
#This directory must point to location to save the 
out_directory = "Datasets/Simulation1.csv"

###########################################################################################
################################## Code ###################################################
###########################################################################################

data = pd.read_csv(directory) 

#removing constant column
data = data.loc[:,(data != data.iloc[0]).any()] 

#extract column name (except the first one)
names = data.columns[1:]

#convert to numpy 
datatemp      = data.to_numpy()

#Extract first column to index
index    = datatemp[:,0]
datatemp = datatemp[:,1:]

#add some white noise
(n,l) = datatemp.shape
random_matrix = np.random.rand(n,l) * (10**(-8))
datatemp      = datatemp + random_matrix

#return data into a dataframe
data = pd.DataFrame(datatemp)

#rename columns and index
r = []
c = []
for i in names:
    c.append("R" + str(i))
for i in index:
    r.append("T" + str(int(i)))
data.columns = c
data.index   = r

data.to_csv(out_directory)

